name: Tests on unix

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        stability: [prefer-stable]

    name: ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
      - run: pnpm install
      - run: pnpm test
      - run: pnpm coverage

      - name: Send code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
          files: ./coverage/clover.xml
